import type { Metadata } from "next";
import { Lato ,Anton } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const lato = Lato({ subsets: ["latin"], weight:["100","300","400","700","900"],variable:"--font-lato" });
const anton = Anton({subsets:["latin"],weight:["400"],variable:"--font-anton"})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${anton.variable} relative`}>
      <Header/>
      <Navbar/>
        {children}
      <Footer/>
        </body>
    </html>
  );
}
